import * as THREE from 'three'
import { CHALLENGE } from '../config.js'
import { BLOCKS, isSolid } from '../world/blocks.js'

// King's Trial stage 2 — Raise the Beacon: the structure spec + checker. The
// cell list comes expanded from config (CHALLENGE.beacon.cells, generated by
// beaconCells from the captain-retunable shape); each cell is an offset from
// the anchor with an allowed-id list (null = any solid block). evaluate()
// reads world.blockAt per cell — the edit overlay answers even for unloaded
// chunks, so the check is correct at any distance — and is forgiving in
// materials/extras/terrain but strict in shape and the signature cells.
//
// dy 0 is the anchor column's SURFACE BLOCK layer (base y = terrainHeight -
// 1), so the platform sits flush with the ground and natural terrain
// satisfies platform cells for free — that reads as smart, not cheaty.
//
// The ghost preview is one InstancedMesh of translucent additive cubes — one
// draw call however many cells — built lazily on show() (a sealed or finished
// stage renders nothing) and refreshed by zero-scaling satisfied instances.
export class StructureCheck {
  constructor(world, scene, anchor, cfg = CHALLENGE.beacon) {
    this.world = world
    this.scene = scene
    this.cfg = cfg
    this.anchorX = anchor.x
    this.anchorZ = anchor.z
    this.baseY = anchor.y - 1 // the anchor column's surface block
    this.cells = cfg.cells.map((cell) => ({ ...cell, satisfied: false }))
    this.satisfied = 0
    this.onCellSatisfied = null // callback({x, y, z} cell center) — pulse fx
    this.ghost = null // the InstancedMesh, alive only while showing
  }

  get total() {
    return this.cells.length
  }

  get isComplete() {
    return this.satisfied === this.cells.length
  }

  // Should a world edit at (wx, wz) re-run the check? Cheap horizontal box
  // around the anchor — explosions report their center, so the radius has
  // ample margin over blast size + structure extent.
  near(wx, wz) {
    const r = this.cfg.checkRadius
    return Math.abs(wx - this.anchorX) <= r && Math.abs(wz - this.anchorZ) <= r
  }

  // Re-test every cell against the live world. Cells flipping unsatisfied →
  // satisfied fire the pulse hook; cells knocked back out (a broken block
  // before completion) just re-show their ghost. Returns true when the whole
  // spec is satisfied — latching is the owner's (Challenge's) job.
  evaluate() {
    const newlySatisfied = []
    let count = 0
    for (const cell of this.cells) {
      const id = this.world.blockAt(
        this.anchorX + cell.dx,
        this.baseY + cell.dy,
        this.anchorZ + cell.dz,
      )
      const ok = cell.ids ? cell.ids.includes(id) : isSolid(id)
      if (ok && !cell.satisfied) newlySatisfied.push(cell)
      cell.satisfied = ok
      if (ok) count++
    }
    this.satisfied = count
    this.#refreshGhost()
    for (const cell of newlySatisfied) this.onCellSatisfied?.(this.#cellCenter(cell))
    return this.isComplete
  }

  #cellCenter(cell) {
    return {
      x: this.anchorX + cell.dx + 0.5,
      y: this.baseY + cell.dy + 0.5,
      z: this.anchorZ + cell.dz + 0.5,
    }
  }

  // Human-readable bill of materials for the quest log, derived from the
  // shape so captain retunes never drift from the text.
  billOfMaterials() {
    const { shape } = this.cfg
    const names = (ids) => ids.map((id) => BLOCKS[id].name.toLowerCase()).join('/')
    return [
      `a ${shape.platformSize}×${shape.platformSize} floor of any solid blocks`,
      `4 corner pillars ${shape.pillarHeight} high (${names(shape.pillarIds)})`,
      `a ${BLOCKS[shape.torchId].name.toLowerCase()} atop each pillar`,
      `${shape.coreHeight} ${BLOCKS[shape.coreId].name.toLowerCase()} stacked at the heart`,
    ]
  }

  // --- Ghost preview (built lazily on stage entry) ---------------------------

  show() {
    if (this.ghost) return
    const { color, opacity } = this.cfg.ghost
    // Slightly oversized cubes so a WRONG block filling a cell reads as
    // haloed by its ghost instead of z-fighting it.
    this.ghost = new THREE.InstancedMesh(
      new THREE.BoxGeometry(1.02, 1.02, 1.02),
      new THREE.MeshBasicMaterial({
        color,
        transparent: true,
        opacity,
        blending: THREE.AdditiveBlending,
        depthWrite: false,
      }),
      this.cells.length,
    )
    this.scene.add(this.ghost)
    this.#refreshGhost()
  }

  hide() {
    if (!this.ghost) return
    this.scene.remove(this.ghost)
    this.ghost.geometry.dispose()
    this.ghost.material.dispose()
    this.ghost.dispose()
    this.ghost = null
  }

  // Satisfied cells collapse to zero scale (InstancedMesh has no per-instance
  // visibility); unsatisfied ones sit at their world cell.
  #refreshGhost() {
    if (!this.ghost) return
    const m = new THREE.Matrix4()
    const zero = new THREE.Matrix4().makeScale(0, 0, 0)
    for (const [i, cell] of this.cells.entries()) {
      if (cell.satisfied) {
        this.ghost.setMatrixAt(i, zero)
      } else {
        const c = this.#cellCenter(cell)
        this.ghost.setMatrixAt(i, m.makeTranslation(c.x, c.y, c.z))
      }
    }
    this.ghost.instanceMatrix.needsUpdate = true
  }
}
